### ISSUE TITLE
How can I update the links all over the vaults?

### ISSUE THREAD

**Issue by nnkn** [trganda/obsidian-attachment-management#42]
hi ,thank you for you great plugin. and I want to update all the images attached , how can I do it ? I only can update them one by one ,but I have thousands of files to update...

**Comment by trganda** [comment]
You can try command with `Rearrange all linked attachments`, remeber backup the vault first (It's a experimental feature).

**Comment by nnkn** [comment]
> You can try command with `Rearrange all linked attachments`, remeber backup the vault first (It's a experimental feature).

![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/db80e317-f014-4249-9fc5-f3a2286f1172)
I tried this, but it only affects  the file I opened(not all the vault), according to the description ,  I  think it will rearrange more files than just img.

**Comment by trganda** [comment]
`Rearrange all linked attachments` should be working on all `md` or `canvas` files of your vault (I have tested on my vault). But, it only rename the img file default. To rename all type file, enable the handle all and add a exclude extension pattern if you need.

Btw, update to [0.7.4](https://github.com/trganda/obsidian-attachment-management/releases/tag/0.7.4). I have fixed a bug of handle all.

**Comment by nnkn** [comment]
> 

I'm afraid there's some plugins conflicts with your plugin. because after I updated the pluging to 0.7.4 and restart the obsidian. `Rearrange all linked attachments` still only affects the opened file.
I will try to disable all the plugins and only enable yours to test if so.

**Comment by nnkn** [comment]
origin:
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/245291ad-38fd-4844-a304-676936f04b25)
after `Rearrange all linked attachments` command
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/1958e358-9308-46e1-bac7-87a64f1fa20b)
after `Rearrange linked attachments` command
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/be66c114-d64d-43a2-8222-4f34020e39a8)

**Comment by nnkn** [comment]
as the pic above. I disabled all the plugins except the attachment management, and use the command to see the effect.
the `Rearrange all linked attachments` command don't work.
My language is Chinese , is this effected?

**Comment by trganda** [comment]
你好，目录或者文件名为中文应该不影响，我的 vault 中也会使用中文。这两个命令使用的同一个api，按到理 `Rearrange all linked attachments` 不应该不生效。我在mac和windows中都没有复现出你描述的问题。

麻烦提供一下以下信息：

你的操作系统版本
Obsidian 版本
插件的 `data.json` 文件内容，位于 `.obsidian/plugins/attachment-management/data.json`

另外，下面的压缩文件里有一个 debug 版本的 main.js 文件，如果你愿意，可以在检查 main.js 的校验值以及文件内容安全后，把它拷贝至 `.obsidian/plugins/attachment-management/main.js`，覆盖已有文件。
[dubug_version.zip](https://github.com/trganda/obsidian-attachment-management/files/12208754/dubug_version.zip)
覆盖后，在 Obsidian 中重新启用插件，并确保插件设置正确，按 Option+Command+I（Mac） 或 Ctrl+Shift+I（Windows） 打开开发者模式。

先点击下图中框起来的按钮，清除控制台内容

<img width="360" alt="image" src="https://github.com/trganda/obsidian-attachment-management/assets/62204882/1aa40cb0-aeaa-499a-bda4-9612e4c93e1e">

之后再尝试复现你遇到的问题，并将控制台的输出（调试输出到日志会包含你 vault 中的文件的路径名，如果有敏感信息的话，可以新创建一个空的 vault 再尝试），粘贴后存入文件再上传到评论里。

**Comment by nnkn** [comment]
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/eb7ab8f0-1f5f-42a1-902b-11d285fedb2a)
刚才新建了一个空的仓库，啥都没做，只装了你的插件，运行了一下`Rearrange all linked attachments`，可以了，可能是和什么冲突了吧，我再排查排查。

## 我的操作系统版本
~~~sh
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎6/‎7
操作系统版本	22621.2070
体验	Windows Feature Experience Pack 1000.22659.1000.0
~~~
## Obsidian 版本
1.3.5
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/f7c5a094-0ffb-40d6-a164-372710432de1)

## 插件的 data.json 文件内容，位于 .obsidian/plugins/attachment-management/data.json
新建的仓库里没有这个文件，
旧的仓库里的文件内容是：
~~~json
{
  "attachPath": {
    "attachmentRoot": "",
    "saveAttE": "obsFolder",
    "attachmentPath": "imgs/${notepath}/${notename}",
    "attachFormat": "IMG-${date}",
    "type": "GLOBAL"
  },
  "dateFormat": "YYYYMMDDHHmmssSSS",
  "handleAll": false,
  "excludeExtensionPattern": "",
  "autoRenameAttachment": true,
  "excludedPaths": "",
  "excludePathsArray": [],
  "excludeSubpaths": false,
  "overridePath": {}
}
~~~

## 调试输出内容如下（我只截图了出错的部分，前面的正常部分点开实在是太多了，而且全选复制只能复制到看得到的，展开后的内容无法复制到）：
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/d9a311ee-8434-4d05-bfe0-441cadeba69c)

前面的内容是这样的：
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/b2bf9392-b59c-4fcc-a52f-67793942e3d5)

辛苦你了！如果还有什么需要我提供的话，直接说就行，感谢感谢！！

**Comment by nnkn** [comment]
## 这是所有的代码
~~~sh
05:48:26.221 getAttachmentsInVaultByLinks - allFiles: 3517 (3517) [t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, t, …]
plugin:attachment-management:53 05:48:26.228 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.241 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.242 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.243 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.244 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.245 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.246 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.247 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.248 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.248 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.249 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.250 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.251 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.259 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.260 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.265 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.266 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.267 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.268 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.269 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.270 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.271 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.271 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.272 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.273 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.273 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.274 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.275 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.275 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.276 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.276 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.277 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.278 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.278 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.279 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.279 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.280 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.280 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.281 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.282 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.282 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.283 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.283 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.284 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.285 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.285 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.286 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.287 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.287 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.288 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.289 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.290 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.291 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.292 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.293 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.294 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.295 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.295 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.296 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.298 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.298 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.299 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.300 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.301 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.302 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.303 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.303 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.304 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.304 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.305 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.306 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.306 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.307 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.307 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.308 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.308 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.309 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.310 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.310 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.311 excludePathsArray:  []
plugin:attachment-management:53 05:48:26.311 excludePathsArray:  []
plugin:attachment-management:924 Uncaught (in promise) TypeError: Cannot read properties of null (reading '1')
    at ArrangeHandler.getAttachmentsInVaultByLinks (plugin:attachment-management:924:67)
    at async ArrangeHandler.getAttachmentsInVault (plugin:attachment-management:862:25)
    at async ArrangeHandler.rearrangeAttachment (plugin:attachment-management:803:25)
g
~~~
## 我数了一下，貌似是第82个文件出了问题的样子？从0开始编的话就是81号
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/b73b020d-ac7f-47a9-94ae-a48fe16f152a)
我找到了这个文件，对它单独使用命令`Rearrange linked attachments`，正常处理了
然后我再回头去运行`Rearrange all linked attachments`，还是一样的错误，是我的文件找错了吗？

**Comment by nnkn** [comment]
继续
原来是我算错了，实际出错的是80号文件，我把80号文件改扩展名后直接运行单文件处理，果然报错
~~~sh
06:10:03.231 excludePathsArray:  []
plugin:attachment-management:53 06:10:03.232 getAttachmentsInVaultByLinks - active file: 黑群晖/DOCKER重新编译php的gd扩展以支持webp格式.md
plugin:attachment-management:53 06:10:03.232 getAttachmentsInVaultByLinks - resolvedLinks: {黑群晖/DOCKER重新编译php的gd扩展以支持webp格式.md: {…}}
plugin:attachment-management:53 06:10:03.232 getAttachmentsInVaultByLinks - allFiles: 1 [t]
plugin:attachment-management:53 06:10:03.232 excludePathsArray:  []
plugin:attachment-management:924 Uncaught (in promise) TypeError: Cannot read properties of null (reading '1')
    at ArrangeHandler.getAttachmentsInVaultByLinks (plugin:attachment-management:924:67)
    at ArrangeHandler.getAttachmentsInVault (plugin:attachment-management:862:36)
    at ArrangeHandler.rearrangeAttachment (plugin:attachment-management:803:36)
    at Object.callback (plugin:attachment-management:1240:53)
    at f_ (app.js:1:1728995)
    at t.onChooseItem (app.js:1:2314274)
    at t.onChooseSuggestion (app.js:1:1868531)
    at t.selectSuggestion (app.js:1:1868081)
    at e.useSelectedItem (app.js:1:792982)
    at e.onSuggestionClick (app.js:1:792718)
g
~~~
## 我不知道是啥意思，这个文件比较大，我就又排查出一个报错的文件，这个文件内容少，直接可以贴上来：
~~~md
---
aliases: chevereto图床不支持上传webp格式的图片的解决办法
tags:
  - 黑群晖
date: '2020-10-05T07:54:06'
date_updated: '2021-04-10T13:03:28'

---

# chevereto图床不支持上传webp格式的图片的解决办法

Google之，发现是php7.3版本的gd扩展不支持webp格式，那么，重新编译一下gd扩展，让他支持就可以了

> webp格式是google出品的一种高效图片压缩格式，跟jpeg类似,是有损压缩，但体积会比jpeg平均减少40%以上

[[DOCKER重新编译php的gd扩展以支持webp格式]]


~~~

## 报错内容
~~~sh
06:11:25.260 excludePathsArray:  []
plugin:attachment-management:53 06:11:25.260 getAttachmentsInVaultByLinks - active file: 黑群晖/chevereto图床不支持上传webp格式的图片的解决办法.md
plugin:attachment-management:53 06:11:25.260 getAttachmentsInVaultByLinks - resolvedLinks: {黑群晖/chevereto图床不支持上传webp格式的图片的解决办法.md: {…}}
plugin:attachment-management:53 06:11:25.260 getAttachmentsInVaultByLinks - allFiles: 1 [t]
plugin:attachment-management:53 06:11:25.261 excludePathsArray:  []
plugin:attachment-management:924 Uncaught (in promise) TypeError: Cannot read properties of null (reading '1')
    at ArrangeHandler.getAttachmentsInVaultByLinks (plugin:attachment-management:924:67)
    at ArrangeHandler.getAttachmentsInVault (plugin:attachment-management:862:36)
    at ArrangeHandler.rearrangeAttachment (plugin:attachment-management:803:36)
    at Object.callback (plugin:attachment-management:1240:53)
    at f_ (app.js:1:1728995)
    at t.onChooseItem (app.js:1:2314274)
    at t.onChooseSuggestion (app.js:1:1868531)
    at t.selectSuggestion (app.js:1:1868081)
    at e.useSelectedItem (app.js:1:792982)
    at Object.func (app.js:1:790578)
g
~~~

**Comment by nnkn** [comment]
我把这个文件复制到新开的仓库里，依然报错
![image](https://github.com/trganda/obsidian-attachment-management/assets/22342244/ff86231d-af7b-46f6-b0ea-57bb5ea93908)

**Comment by trganda** [comment]
笑死，我试了一下，在自己常用的 vault 上也遇到这个错误信息了。

非常感谢你提供的信息！我今天会抽时间看看问题出在哪里的。

**Comment by nnkn** [comment]
> 笑死，我试了一下，在自己常用的 vault 上也遇到这个错误信息了。
> 
> 非常感谢你提供的信息！我今天会抽时间看看问题出在哪里的。

好的，谢谢！！

**Comment by trganda** [comment]
> > 笑死，我试了一下，在自己常用的 vault 上也遇到这个错误信息了。
> > 非常感谢你提供的信息！我今天会抽时间看看问题出在哪里的。
> 
> 好的，谢谢！！

你好，更新到 [0.7.6](https://github.com/trganda/obsidian-attachment-management/releases/tag/0.7.6) 版本再试试。

**Comment by nnkn** [comment]
> > > 笑死，我试了一下，在自己常用的 vault 上也遇到这个错误信息了。
> > > 非常感谢你提供的信息！我今天会抽时间看看问题出在哪里的。
> > 
> > 
> > 好的，谢谢！！
> 
> 你好，更新到 [0.7.6](https://github.com/trganda/obsidian-attachment-management/releases/tag/0.7.6) 版本再试试。

正常了，感谢感谢！！
